"""Generation of the RBAC admin panel, on request.

The panel - the user directory at `/admin`, the roles, permissions and groups
screens, and the CRUD builder - used to ship inside every project, because the
framework repository was the starting point. A bare project generated by
`craft new` has none of it, and `craft make:admin` puts it back for the
projects that want it.

Templates live as real files under `admin_templates/`, suffixed `.stub` so the
test collector and the import system ignore them, and are copied verbatim.
This module never builds source or markup out of strings: governance forbids
markup inside Python, and a generator that assembles views by concatenation is
exactly that with an extra step.

What the command writes:

- the admin controllers, the panel shell they render through, and the CRUD
  builder form request;
- the `Role`, `Permission` and `Group` models;
- one migration carrying every RBAC and ABAC table;
- the Forge views for each screen;
- the `/admin/*` routes, appended to `routes/web.py` behind `auth` and
  `role:admin`;
- the `role`, `permission` and `group` entries under `models` in
  `config/auth.py`, which is where the engine resolves identity models from
  (`engine/auth/registry.py`).
"""

from __future__ import annotations

import os
import re
import shutil
from typing import Any, Dict, Final, List, Optional

from engine.cli import identity_config, layout_scaffolder

#: Root of the template tree, alongside this module.
ADMIN_TEMPLATE_ROOT: Final[str] = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "admin_templates"
)

#: Suffix marking a template file. Stripped when the file is written out.
STUB_SUFFIX: Final[str] = ".stub"

#: Heading written above the appended route block the first time.
ROUTES_MARKER: Final[str] = "# Admin Panel Routes (make:admin)"

#: Presence of this call in `routes/web.py` means the panel is already
#: registered. Detection is a token search rather than a rewrite: the route
#: file belongs to the project, and a generator that reformats it destroys
#: work it did not write.
ROUTES_TOKEN: Final[str] = 'Route.get("/admin", [HomeController, "admin"])'

#: Written when `routes/web.py` is absent, so the appended block has the
#: `Route` facade in scope.
ROUTES_HEADER: Final[str] = '"""Web routes."""\n\nfrom craft.facades import Route\n'

#: Import lines the appended routes need.
ROUTE_IMPORTS: Final[List[str]] = [
    "from app.Http.Controllers.Admin.CrudBuilderController import CrudBuilderController",
    "from app.Http.Controllers.Admin.GroupController import GroupController",
    "from app.Http.Controllers.Admin.HomeController import HomeController",
    "from app.Http.Controllers.Admin.RoleController import PermissionController, RoleController",
]

#: The panel's routes. Every one of them hands out or displays access, so they
#: all carry `role:admin` on top of `auth`: authentication is not
#: authorization, and this surface lists every account in the installation.
ROUTE_BLOCK: Final[str] = '''
Route.get("/admin", [HomeController, "admin"]).middleware("auth", "role:admin").name("admin.dashboard")
Route.get("/admin/crud-builder", [CrudBuilderController, "index"]).middleware("auth", "role:admin").name(
    "admin.crud_builder.index"
)
Route.post("/admin/crud-builder", [CrudBuilderController, "store"]).middleware("auth", "role:admin").name(
    "admin.crud_builder.store"
)
Route.get("/admin/roles", [RoleController, "index"]).middleware("auth", "role:admin").name("admin.roles.index")
Route.post("/admin/roles/grant", [RoleController, "grant"]).middleware("auth", "role:admin").name("admin.roles.grant")
Route.get("/admin/permissions", [PermissionController, "index"]).middleware("auth", "role:admin").name(
    "admin.permissions.index"
)
Route.get("/admin/groups", [GroupController, "index"]).middleware("auth", "role:admin").name("admin.groups.index")
Route.post("/admin/groups", [GroupController, "store"]).middleware("auth", "role:admin").name("admin.groups.store")
Route.post("/admin/groups/members", [GroupController, "add_member"]).middleware("auth", "role:admin").name(
    "admin.groups.members"
)
Route.post("/admin/groups/roles", [GroupController, "grant_role"]).middleware("auth", "role:admin").name(
    "admin.groups.roles"
)
Route.post("/admin/groups/permissions", [GroupController, "grant_permission"]).middleware("auth", "role:admin").name(
    "admin.groups.permissions"
)
'''

#: Package directories the generated files live in, each needing an
#: `__init__.py` to be importable.
PACKAGE_DIRECTORIES: Final[List[str]] = [
    os.path.join("app", "Http", "Controllers", "Admin"),
    os.path.join("app", "Http", "Controllers", "Panel"),
    os.path.join("app", "Http", "Requests"),
    os.path.join("app", "Models"),
]

#: Identity models this command provides, by the kind `engine/auth/registry.py`
#: resolves. Written into `config/auth.py` under `models`.
IDENTITY_MODELS: Final[Dict[str, str]] = {
    "role": "app.Models.Role.Role",
    "permission": "app.Models.Permission.Permission",
    "group": "app.Models.Group.Group",
}


def _template_files() -> List[str]:
    """List every template file, as paths relative to the template root.

    Returns:
        Relative paths, sorted so generation order is deterministic.
    """
    found: List[str] = []
    for directory, _, filenames in os.walk(ADMIN_TEMPLATE_ROOT):
        for filename in filenames:
            if not filename.endswith(STUB_SUFFIX):
                continue
            absolute = os.path.join(directory, filename)
            found.append(os.path.relpath(absolute, ADMIN_TEMPLATE_ROOT))
    return sorted(found)


def _copy_templates(base_path: str, *, force: bool) -> Dict[str, str]:
    """Copy every template into the project.

    Args:
        base_path: Root of the target project.
        force: Overwrite files that already exist.

    Returns:
        A mapping of project-relative path to absolute path, for each file
        written.

    Raises:
        FileExistsError: If a destination exists and `force` is False.
    """
    written: Dict[str, str] = {}
    for relative_template in _template_files():
        relative_output = relative_template[: -len(STUB_SUFFIX)]
        destination = os.path.join(base_path, relative_output)
        if os.path.exists(destination) and not force:
            raise FileExistsError(destination)
        os.makedirs(os.path.dirname(destination), exist_ok=True)
        shutil.copyfile(os.path.join(ADMIN_TEMPLATE_ROOT, relative_template), destination)
        written[relative_output] = destination
    return written


def _write_package_markers(base_path: str, written: Dict[str, str]) -> None:
    """Create an empty `__init__.py` in each generated package directory.

    Args:
        base_path: Root of the target project.
        written: Accumulator mapping a project-relative path to its absolute
            path; mutated in place.
    """
    for package in PACKAGE_DIRECTORIES:
        directory = os.path.join(base_path, package)
        os.makedirs(directory, exist_ok=True)
        marker = os.path.join(directory, "__init__.py")
        if os.path.exists(marker):
            continue
        with open(marker, "w", encoding="utf-8") as handle:
            handle.write("")
        written[os.path.join(package, "__init__.py")] = marker


def _read_routes(base_path: str) -> str:
    """Return the current contents of `routes/web.py`, or a fresh header.

    Args:
        base_path: Root of the target project.

    Returns:
        The file's contents, or the header written for a project that has no
        route file yet.
    """
    routes_path = os.path.join(base_path, "routes", "web.py")
    if not os.path.isfile(routes_path):
        return ROUTES_HEADER
    with open(routes_path, "r", encoding="utf-8") as handle:
        return handle.read()


def is_registered(base_path: str) -> bool:
    """Report whether the panel's routes are already in `routes/web.py`.

    Args:
        base_path: Root of the target project.

    Returns:
        True when the dashboard route is declared.
    """
    return ROUTES_TOKEN in _read_routes(base_path)


def register_admin_routes(base_path: str) -> str:
    """Append the `/admin/*` routes to `routes/web.py`.

    Append-only and idempotent: an existing line is never rewritten, and a
    second run adds nothing, because the dashboard route acts as the token.

    Args:
        base_path: Root of the target project.

    Returns:
        The path to `routes/web.py`.
    """
    routes_path = os.path.join(base_path, "routes", "web.py")
    content = _read_routes(base_path)
    if ROUTES_TOKEN in content:
        return routes_path

    additions = [line for line in ROUTE_IMPORTS if line not in content]
    block = "\n".join(additions) + "\n" + ROUTE_BLOCK
    separator = "\n" if ROUTES_MARKER in content else f"\n\n{ROUTES_MARKER}\n"
    content = content.rstrip("\n") + separator + block

    os.makedirs(os.path.dirname(routes_path), exist_ok=True)
    with open(routes_path, "w", encoding="utf-8") as handle:
        handle.write(content)
    return routes_path


def _fill_model_entries(content: str) -> str:
    """Point the empty `models` entries at the generated classes.

    Only an entry left empty is filled: a project that named its own class
    keeps it.

    Args:
        content: Current contents of `config/auth.py`.

    Returns:
        The updated contents.
    """
    for kind, dotted_path in IDENTITY_MODELS.items():
        pattern = rf'(["\']{kind}["\']\s*:\s*)["\']["\']'
        content = re.sub(pattern, rf'\g<1>"{dotted_path}"', content)
    return content


def _model_block() -> str:
    """Return a `models` block naming the generated classes.

    Written only into a `config/auth.py` that has no `models` mapping at all.

    Returns:
        The Python source of the block, including its explanatory comment.
    """
    entries = "".join(f'    "{kind}": "{path}",\n' for kind, path in IDENTITY_MODELS.items())
    return (
        "\n# Identity models generated by `craft make:admin`, resolved by the engine\n"
        "# through `craft.auth.registry`.\n"
        f"models = {{\n{entries}}}\n"
    )


def configure_identity_models(base_path: str) -> Optional[str]:
    """Record the generated models in `config/auth.py`.

    The engine resolves `Role`, `Permission` and `Group` from configuration
    rather than importing `app.Models.*`, so a panel whose models are not
    declared there is a panel whose console commands do not register.

    Args:
        base_path: Root of the target project.

    Returns:
        The path to `config/auth.py`, or None when the project has no such
        file.
    """
    return identity_config.record_models(base_path, IDENTITY_MODELS)


def build_admin(base_path: str, *, force: bool = False) -> Dict[str, Any]:
    """Generate the admin panel into a project.

    Args:
        base_path: Root of the target project.
        force: Overwrite files the panel also provides.

    Returns:
        A mapping with `files` (project-relative path to absolute path) and,
        when the panel was already registered, `already_configured` set to
        True and nothing written.

    Raises:
        FileExistsError: If a generated file exists and `force` is False.
    """
    if is_registered(base_path) and not force:
        return {"files": {"routes": os.path.join(base_path, "routes", "web.py")}, "already_configured": True}

    # Generated views extend `layouts.app`; without the shell every one of
    # them raises at render time. Written only when the project has none.
    written = _copy_templates(base_path, force=force)
    layout_path = layout_scaffolder.ensure_layout(base_path, force=force)
    if layout_path is not None:
        written[layout_scaffolder.LAYOUT_RELATIVE_PATH] = layout_path
    _write_package_markers(base_path, written)
    written["routes/web.py"] = register_admin_routes(base_path)
    config_path = configure_identity_models(base_path)
    if config_path is not None:
        written["config/auth.py"] = config_path
    return {"files": written, "already_configured": False}
