"""
Generators — Stub-based code generators backing the `dev.py make:*` commands
(models, controllers, migrations, requests, resources, jobs, events, ...).
Category: Core Framework (CLI).
Relations:
  - Invoked from `engine/cli/app.py`; refuses to overwrite existing files
    unless `--force` is passed.
References:
  - Guide: `documentation/cli.md#generators`
"""
# Craft Framework
# Copyright (c) 2026 Antonio Santos <snarthost@gmail.com>
# Licensed under the MIT License. See LICENSE in the project root.

from __future__ import annotations

import os
import re
from typing import Dict, List, Optional, Tuple

from engine.support.naming import plural, snake, table_for  # noqa: E402,F401  re-exported


def studly(value: str) -> str:
    parts = re.split(r"[_\-\s]+", value)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


# -- stubs ---------------------------------------------------------------------

def model_stub(name: str, fields: Optional[List[dict]] = None) -> str:
    fillable = [f["name"] for f in (fields or [])]
    fillable_repr = "[" + ", ".join(repr(n) for n in fillable) + "]" if fillable else "[]"
    return f'''"""{name} model."""

from craft.orm.model import Model


class {name}(Model):
    __table__ = "{table_for(name)}"

    fillable = {fillable_repr}
    hidden = []
'''


def controller_stub(name: str, resource: bool = False) -> str:
    if not resource:
        return f'''"""{name}."""

from craft.http.controller import Controller


class {name}(Controller):
    async def index(self, request):
        return self.json({{"data": []}})
'''

    return f'''"""{name} — resource controller."""

from craft.http.controller import Controller


class {name}(Controller):
    async def index(self, request):
        """GET / — list records."""
        return self.json({{"data": []}})

    async def show(self, request, id):
        """GET /{{id}} — show a single record."""
        return self.json({{"data": None}})

    async def store(self, request):
        """POST / — create a record."""
        return self.json({{"data": None}}, status=201)

    async def update(self, request, id):
        """PUT /{{id}} — update a record."""
        return self.json({{"data": None}})

    async def destroy(self, request, id):
        """DELETE /{{id}} — remove a record."""
        return self.json(None, status=204)
'''


def crud_controller_stub(name: str, model: str, request: str, resource: str) -> str:
    """A resource controller wired to a real Model/FormRequest/Resource trio.

    Unlike `controller_stub(resource=True)` — a bare scaffold meant to be
    filled in by hand — this is meant to be immediately usable: it actually
    queries the model instead of returning placeholder data.
    """
    return f'''"""{name} — resource controller generated by the CRUD builder."""

from craft.http.controller import Controller
from craft.http.response import Response
from app.Models.{model} import {model}
from app.Http.Requests.{request} import {request}
from app.Http.Resources.{resource} import {resource}


class {name}(Controller):
    async def index(self, request):
        """GET / — list records."""
        per_page = min(int(request.input("per_page", 15) or 15), 100)
        records = {model}.query().paginate(per_page)
        return {resource}.collection(records).response()

    async def show(self, request, id):
        """GET /{{id}} — show a single record."""
        record = {model}.find(id)
        if record is None:
            return Response("Not found", status=404)
        return {resource}(record).response()

    async def store(self, request):
        """POST / — create a record."""
        data = {request}(request).validated()
        record = {model}.create(data)
        return {resource}(record).response(status=201)

    async def update(self, request, id):
        """PUT /{{id}} — update a record."""
        record = {model}.find(id)
        if record is None:
            return Response("Not found", status=404)
        data = {request}(request).validated()
        record.update_attributes(data)
        return {resource}(record).response()

    async def destroy(self, request, id):
        """DELETE /{{id}} — remove a record."""
        record = {model}.find(id)
        if record is None:
            return Response("Not found", status=404)
        record.delete()
        return self.no_content()
'''


def middleware_stub(name: str) -> str:
    return f'''"""{name} middleware."""


class {name}:
    async def handle(self, request, call_next):
        response = await call_next(request)
        return response
'''


def request_stub(name: str, fields: Optional[List[dict]] = None) -> str:
    if not fields:
        return f'''"""{name} form request."""

from craft.validation.form_request import FormRequest


class {name}(FormRequest):
    def authorize(self) -> bool:
        # Require an authenticated user by default — mirror this pattern in
        # your own FormRequests instead of returning `True` unconditionally.
        return self.user() is not None
        # TODO: also check ownership once the model has a user_id column,
        # e.g. `self.user().id == record.get_attribute("user_id")`.

    def rules(self) -> dict:
        return {{
            # "field": ["required", "string"],
        }}
'''

    rule_lines = []
    for field in fields:
        rules = field.get("rules")
        if not rules:
            rules = ["nullable"] if field.get("nullable", True) else ["required"]
        rule_lines.append(f'            "{field["name"]}": {rules!r},')
    rules_body = "\n".join(rule_lines)
    return f'''"""{name} form request."""

from craft.validation.form_request import FormRequest


class {name}(FormRequest):
    def authorize(self) -> bool:
        # Require an authenticated user by default — mirror this pattern in
        # your own FormRequests instead of returning `True` unconditionally.
        return self.user() is not None
        # TODO: also check ownership once the model has a user_id column,
        # e.g. `self.user().id == record.get_attribute("user_id")`.

    def rules(self) -> dict:
        return {{
{rules_body}
        }}
'''


def resource_stub(name: str, fields: Optional[List[dict]] = None) -> str:
    if not fields:
        return f'''"""{name} API resource."""

from craft.resources import Resource


class {name}(Resource):
    def to_array(self, request=None) -> dict:
        return {{
            "id": self.resource.get_attribute("id"),
        }}
'''

    field_lines = "\n".join(
        f'            "{field["name"]}": self.resource.get_attribute("{field["name"]}"),'
        for field in fields
    )
    return f'''"""{name} API resource."""

from craft.resources import Resource


class {name}(Resource):
    def to_array(self, request=None) -> dict:
        return {{
            "id": self.resource.get_attribute("id"),
{field_lines}
            "created_at": str(self.resource.get_attribute("created_at")) if self.resource.get_attribute("created_at") else None,
            "updated_at": str(self.resource.get_attribute("updated_at")) if self.resource.get_attribute("updated_at") else None,
        }}
'''


#: DDL field type -> HTML `<input type="...">`, for fields that are not
#: rendered as a checkbox or textarea.
_HTML_INPUT_TYPES: Dict[str, str] = {
    "integer": "number",
    "big_integer": "number",
    "small_integer": "number",
    "float": "number",
    "decimal": "number",
    "date": "date",
    "datetime": "datetime-local",
}


def _field_input_html(field: dict, value_expr: str) -> str:
    """One labeled form control for `field`, matching `posts/create.forge.py`'s
    markup (Tailwind-esque utility classes, a `label`/control pair per field).

    `value_expr` is the Forge/Jinja expression used to prefill the control —
    `old('name')` on create, `old('name') or record.get_attribute('name')` on
    edit, matching the `old()`-based redisplay pattern in
    `posts/edit.forge.py`.
    """
    name = field["name"]
    label = name.replace("_", " ").title()
    type_ = field.get("type", "string")
    required = "required" in (field.get("rules") or [])
    required_attr = " required" if required else ""

    if type_ == "boolean":
        return (
            '        <div>\n'
            f'            <input type="checkbox" name="{name}" id="{name}" value="1" '
            f'{{% if {value_expr} %}}checked{{% endif %}}>\n'
            f'            <label for="{name}">{label}</label>\n'
            '        </div>'
        )

    if type_ in ("text", "long_text"):
        return (
            '        <div>\n'
            f'            <label for="{name}">{label}</label>\n'
            f'            <textarea name="{name}" id="{name}" rows="6"{required_attr}>'
            f'{{{{ {value_expr} }}}}</textarea>\n'
            '        </div>'
        )

    if type_ == "json":
        return (
            '        <div>\n'
            f'            <label for="{name}">{label}</label>\n'
            f'            <textarea name="{name}" id="{name}" rows="4" placeholder=\'{{"key": "value"}}\' '
            f'{required_attr}>{{{{ {value_expr} }}}}</textarea>\n'
            '            <p>JSON formatted data.</p>\n'
            '        </div>'
        )

    html_type = _HTML_INPUT_TYPES.get(type_, "text")
    step_attr = ' step="any"' if type_ in ("float", "decimal") else ""
    return (
        '        <div>\n'
        f'            <label for="{name}">{label}</label>\n'
        f'            <input type="{html_type}" name="{name}" id="{name}" value="{{{{ {value_expr} }}}}"{step_attr} '
        f'{required_attr}>\n'
        '        </div>'
    )



def admin_index_stub(entity: str, slug: str, fields: Optional[List[dict]] = None) -> str:
    """List view for a generated entity's admin UI: one table column per
    field, an edit/delete action per row, and the same dashed-border
    empty-state used by `resources/views/posts/index.forge.py` when there
    are zero records."""
    fields = fields or []
    header_cells = "\n".join(
        f'                            <th>{f["name"].replace("_", " ").title()}</th>'
        for f in fields
    )
    row_cells_lines = []
    for f in fields:
        expr = f"record.get_attribute('{f['name']}')"
        if f.get("type") == "text":
            # Long free-text fields are truncated in the list view — the full
            # value belongs on the edit form, not a table cell.
            row_cells_lines.append(
                f'                                <td>'
                f'{{{{ ({expr} or "")|string|truncate(80) }}}}</td>'
            )
        else:
            row_cells_lines.append(
                f'                                <td>{{{{ {expr} }}}}</td>'
            )
    row_cells_body = "\n".join(row_cells_lines)

    return f'''@extends("layouts.app")

@section("title", "{entity} Records")

@section("content")
<div>
    <div>
        <div>
            <h1>{entity} Records</h1>
            <p>Manage {entity} records</p>
        </div>
        <a href="/admin/{slug}/create">
            New {entity}
        </a>
    </div>

    @if(records is defined and records is not none and records|length > 0)
        <div>
            <div>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
{header_cells}
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(records as record)
                            <tr>
                                <td>{{{{ record.get_attribute('id') }}}}</td>
{row_cells_body}
                                <td>
                                    <a href="/admin/{slug}/{{{{ record.get_attribute('id') }}}}/edit">Edit</a>
                                    <form action="/admin/{slug}/{{{{ record.get_attribute('id') }}}}" method="POST">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button type="submit" onclick="return confirm('Delete this record?')">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @else
        <div>
            <svg fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 18V6A2.25 2.25 0 015.25 3.75h9L18 7.5zm-3 0h.008v.008H15V7.5z"></path>
            </svg>
            <p>No {entity} records yet.</p>
            <p>Be the first to create one!</p>
            <a href="/admin/{slug}/create">
                New {entity}
            </a>
        </div>
    @endif
</div>
@endsection
'''


def admin_form_stub(entity: str, slug: str, fields: Optional[List[dict]] = None, mode: str = "create") -> str:
    """Create/edit form for a generated entity's admin UI.

    `mode` is `"create"` (posts to `/admin/{slug}`, `old()`-only prefill) or
    `"edit"` (posts to `/admin/{slug}/{id}` with a `_method=PUT` override,
    `old() or record.get_attribute()` prefill) — the same two-file split and
    redisplay pattern as `posts/create.forge.py` / `posts/edit.forge.py`.
    """
    fields = fields or []
    is_edit = mode == "edit"

    inputs = []
    for field in fields:
        if is_edit:
            value_expr = f"old('{field['name']}') or record.get_attribute('{field['name']}')"
        else:
            value_expr = f"old('{field['name']}')"
        inputs.append(_field_input_html(field, value_expr))
    inputs_body = "\n\n".join(inputs)

    action = f"/admin/{slug}/{{{{ record.get_attribute('id') }}}}" if is_edit else f"/admin/{slug}"
    method_field = '\n        <input type="hidden" name="_method" value="PUT">' if is_edit else ""
    title = f"Edit {entity}" if is_edit else f"Create {entity}"
    submit_label = f"Update {entity}" if is_edit else f"Create {entity}"

    return f'''@extends("layouts.app")

@section("title", "{title}")

@section("content")
<div>
    <h1>{title}</h1>

    @if(errors|length > 0)
    <div>
        @foreach(errors.values() as messages)
            @foreach(messages as message)
                <p>{{{{ message }}}}</p>
            @endforeach
        @endforeach
    </div>
    @endif

    <form action="{action}" method="POST">
        @csrf{method_field}

{inputs_body}

        <div>
            <button type="submit">
                {submit_label}
            </button>
            <a href="/admin/{slug}">
                Cancel
            </a>
        </div>
    </form>
</div>
@endsection
'''


def admin_controller_stub(entity: str, model: str, request: str, slug: str) -> str:
    """Admin HTML controller for a generated entity — list/create/edit/delete
    server-rendered views, distinct from the JSON API `{model}Controller`
    generated alongside it (different class, different directory, so both
    coexist without a name collision)."""
    return f'''"""{entity} — admin HTML controller generated by the CRUD builder."""

from craft.http.controller import Controller
from craft.http.response import Response, redirect
from app.Models.{model} import {model}
from app.Http.Requests.{request} import {request}


class {entity}(Controller):
    def index(self, request):
        """GET /admin/{slug} — list records."""
        per_page = min(int(request.input("per_page", 15) or 15), 100)
        records = {model}.query().order_by_desc("created_at").paginate(per_page)
        return self.view("admin.{slug}.index", {{"records": records, "show_sidebar": True}})

    def create(self, request):
        """GET /admin/{slug}/create — show the empty form."""
        return self.view("admin.{slug}.create", {{"show_sidebar": True, "errors": {{}}}})

    def store(self, request):
        """POST /admin/{slug} — create a record."""
        form = {request}(request)

        if form.fails():
            self._flash_old_input(request)
            return self.view("admin.{slug}.create", {{"show_sidebar": True, "errors": form.errors}})

        {model}.create(form.validated())
        return redirect(route="admin.{slug}.index")

    def show(self, request, id):
        """GET /admin/{slug}/{{id}} — no standalone show page, go to edit."""
        return redirect(route="admin.{slug}.edit", id=id)

    def edit(self, request, id):
        """GET /admin/{slug}/{{id}}/edit — show the form for an existing record."""
        record = {model}.find(id)
        if record is None:
            return Response("Not found", status=404)
        return self.view("admin.{slug}.edit", {{"record": record, "show_sidebar": True, "errors": {{}}}})

    def update(self, request, id):
        """PUT /admin/{slug}/{{id}} — update a record."""
        record = {model}.find(id)
        if record is None:
            return Response("Not found", status=404)
        form = {request}(request)

        if form.fails():
            self._flash_old_input(request)
            return self.view("admin.{slug}.edit", {{"record": record, "show_sidebar": True, "errors": form.errors}})

        record.update_attributes(form.validated())
        return redirect(route="admin.{slug}.index")

    def destroy(self, request, id):
        """DELETE /admin/{slug}/{{id}} — remove a record."""
        record = {model}.find(id)
        if record is None:
            return Response("Not found", status=404)
        record.delete()
        return redirect(route="admin.{slug}.index")

    # -- helpers -------------------------------------------------------------

    def _flash_old_input(self, request):
        """Flash submitted input so the redisplayed form's `old()` calls can
        restore it, matching `PostController._flash_old_input`."""
        try:
            session = request.session()
        except Exception:
            session = None
        if session is not None:
            session.flash("_old_input", request.all())
'''


def job_stub(name: str) -> str:
    return f'''"""{name} queued job."""

from craft.queue import Job


class {name}(Job):
    def __init__(self, payload=None):
        self.payload = payload

    def handle(self):
        pass
'''


def event_stub(name: str) -> str:
    return f'''"""{name} event."""

from craft.events.event import Event


class {name}(Event):
    def __init__(self, payload=None):
        self.payload = payload
'''


def listener_stub(name: str) -> str:
    return f'''"""{name} event listener."""


class {name}:
    def handle(self, event):
        pass
'''


def policy_stub(name: str) -> str:
    return f'''"""{name} authorization policy.

Every ability denies until you write the rule. A generated policy that
returned True would hand you a file that *looks* like protection while
authorizing everyone — including unauthenticated callers, since `user` may
be None. Fail closed, then open each ability deliberately.
"""


class {name}:
    def view_any(self, user) -> bool:
        return user is not None

    def view(self, user, model) -> bool:
        # Replace with the real rule, e.g.:
        #     return user is not None and model.user_id == user.get_attribute("id")
        return False

    def create(self, user) -> bool:
        return user is not None

    def update(self, user, model) -> bool:
        return False

    def delete(self, user, model) -> bool:
        return False
'''


def seeder_stub(name: str) -> str:
    return f'''"""{name}."""

from craft.seeding import Seeder


class {name}(Seeder):
    def run(self):
        pass
'''


def factory_stub(name: str) -> str:
    model = name[:-7] if name.endswith("Factory") else name
    return f'''"""{name}."""

from craft.factories import Factory
from faker import Faker


class {name}(Factory):
    model = None  # from app.Models.{model} import {model}

    def definition(self) -> dict:
        f = Faker()
        return {{}}
'''


def service_stub(name: str) -> str:
    return f'''"""{name}."""


class {name}:
    pass
'''


#: kind -> (stub builder, destination directory, filename suffix)
GENERATORS: Dict[str, Tuple] = {
    "model": (model_stub, os.path.join("app", "Models"), ""),
    "controller": (controller_stub, os.path.join("app", "Http", "Controllers"), "Controller"),
    "middleware": (middleware_stub, os.path.join("app", "Http", "Middleware"), "Middleware"),
    "request": (request_stub, os.path.join("app", "Http", "Requests"), "Request"),
    "resource": (resource_stub, os.path.join("app", "Http", "Resources"), "Resource"),
    "job": (job_stub, os.path.join("app", "Jobs"), ""),
    "event": (event_stub, os.path.join("app", "Events"), ""),
    "listener": (listener_stub, os.path.join("app", "Listeners"), ""),
    "policy": (policy_stub, os.path.join("app", "Policies"), "Policy"),
    "seeder": (seeder_stub, os.path.join("database", "seeders"), "Seeder"),
    "factory": (factory_stub, os.path.join("database", "factories"), "Factory"),
    "service": (service_stub, os.path.join("app", "Services"), "Service"),
}


def generate(kind: str, name: str, base_path: str, force: bool = False, **options) -> str:
    """Write a generated class file and return its path."""
    if kind not in GENERATORS:
        raise ValueError(f"Unknown generator [{kind}].")

    builder, directory, suffix = GENERATORS[kind]
    class_name = studly(name)
    if suffix and not class_name.endswith(suffix):
        class_name += suffix

    target_dir = os.path.join(base_path, directory)
    os.makedirs(target_dir, exist_ok=True)
    path = os.path.join(target_dir, f"{class_name}.py")

    if os.path.exists(path) and not force:
        raise FileExistsError(path)

    try:
        content = builder(class_name, **options)
    except TypeError:
        content = builder(class_name)

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)

    init_path = os.path.join(target_dir, "__init__.py")
    if not os.path.exists(init_path) and directory.startswith(("app", "database")):
        open(init_path, "a", encoding="utf-8").close()

    return path


def generate_migration(
    name: str,
    base_path: str,
    table: Optional[str] = None,
    create: bool = True,
    force: bool = False,
) -> str:
    """Write a timestamped migration file and return its path.

    Refuses to overwrite unless `force`, like every other generator —
    `documentation/cli.md` promises "generators refuse to overwrite", but this
    one silently clobbered an existing migration, which on a migration is worse
    than on any other file: the old one may already have run in production, so
    the record of what the schema did no longer matches the schema.
    """
    from engine.migrations.migrator import make_migration_stub, migration_filename

    directory = os.path.join(base_path, "database", "migrations")
    os.makedirs(directory, exist_ok=True)

    file_name = migration_filename(snake(name))
    path = os.path.join(directory, file_name)

    if os.path.exists(path) and not force:
        raise FileExistsError(path)

    inferred = table
    if inferred is None:
        match = re.match(r"^create_(\w+)_table$", snake(name))
        if match:
            inferred = match.group(1)
        else:
            match = re.match(r"^(?:add|update|alter)_.*_(?:to|in|on)_(\w+)_table$", snake(name))
            if match:
                inferred = match.group(1)
                create = False
        inferred = inferred or plural(snake(name))

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(make_migration_stub(snake(name), inferred, create))

    return path
