"""The document shell that generated views extend.

Every view `make:auth` and `make:admin` write opens with
`@extends("layouts.app")`, but nothing was writing `layouts/app.forge.py`. In
this repository the demo application happened to provide one, so the gap was
invisible; in a project generated by `craft new` the generated screens raised
at render time instead of showing anything.

The generators call `ensure_layout` so the code they write can run. The layout
is written only when absent: a project that already has one keeps it, because
after the first write the file belongs to the project, not to the engine.

What gets written is a bare HTML document with a title and a content slot. The
skeleton ships no theme, and this does not smuggle one back in.
"""

from __future__ import annotations

import os
import shutil
from typing import Final, Optional

#: The template tree shared by the generators, alongside this module.
SHARED_TEMPLATE_ROOT: Final[str] = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "shared_templates"
)

#: Where the layout lands in the target project, and the name views extend it
#: by: `@extends("layouts.app")` resolves to `layouts/app.forge.py`.
LAYOUT_RELATIVE_PATH: Final[str] = os.path.join("resources", "views", "layouts", "app.forge.py")


def layout_exists(base_path: str) -> bool:
    """Report whether the target project already has the layout.

    Args:
        base_path: Root of the target project.

    Returns:
        True when the layout file is present.
    """
    return os.path.exists(os.path.join(base_path, LAYOUT_RELATIVE_PATH))


def ensure_layout(base_path: str, *, force: bool = False) -> Optional[str]:
    """Write the document shell unless the project already has one.

    Args:
        base_path: Root of the target project.
        force: Overwrite an existing layout. A project that has customised its
            shell loses those changes, so callers pass this only when the
            developer asked for it.

    Returns:
        The path written, or None when an existing layout was left alone.
    """
    destination = os.path.join(base_path, LAYOUT_RELATIVE_PATH)
    if os.path.exists(destination) and not force:
        return None

    os.makedirs(os.path.dirname(destination), exist_ok=True)
    shutil.copyfile(
        os.path.join(SHARED_TEMPLATE_ROOT, "layouts", "app.forge.py.stub"),
        destination,
    )
    return destination
